### ISSUE TITLE
Singularity image

### ISSUE THREAD

**Issue by MengXiao92** [fastmachinelearning/hls4ml-catapult-framework#3]
I am working with the hls4ml, and want to do sth with cataplut, and so glad to watch the repo. But I am newer for Singularity, so
can you share **the Singularity image** containing both Catapult and QuestaSIM, or share how to download the Singularity image?
Thanks！

**Comment by maksgraczyk** [comment]
Firstly, I apologise for a late reply, I did not get any notification about a new issue being posted.

Singularity is software for running programs in containers, similarly to what Docker does. You can check its documentation [here](https://sylabs.io/docs/).

Catapult and QuestaSIM are copyrighted software and require a license in order for them to be used legally. Because of that, I'm afraid I can't share any Singularity images with you. If you happen to have the licenses and installation files (you normally can't download these for free), you can make the image yourself, check the documentation linked above.

As an alternative, you can try out Vivado HLS, which is supported by default in hls4ml without any extra frameworks.

**Comment by MengXiao92** [comment]
Thanks very much，I just have no idea about how to build the image using Singularity for the copyrighted software.

I have installed the righted Catapult and QustaSIM，and  ran the Project Dense019 not using the Image. That is the great project for the research work，thanks a lot.

**Comment by mohamedelhewehy** [comment]
> How this is a great project for research work. you mean by comparison with Catapult Vs Vivado Hls results or what  ?

**Comment by HoesenG** [comment]
How did you run the project without image?
